### ISSUE TITLE
矢量边界

### ISSUE THREAD

**Issue by shepherdmeng** [Mo-Dabao/pyMeteo#1]
中国的矢量边界不对，西藏地区少了一大块
![image](https://user-images.githubusercontent.com/6023344/55397813-a50ce400-5579-11e9-8a92-057b3bac0313.png)

**Comment by Mo-Dabao** [comment]
@shepherdmeng 
github竟然没有提醒我有Issue！！！

我就在https://gadm.org/ 上找的shp文件，也不是知道上哪儿找最标准的。方便的话能提供一份或者告知上哪儿下载吗？

**Comment by zxdawn** [comment]
@Mo-Dabao 因为你没有watch呀;)

**Comment by shepherdmeng** [comment]
非官方出品，仅供参考，算是比较准的


------------------ 原始邮件 ------------------
发件人: "墨大宝"<notifications@github.com>;
发送时间: 2019年5月28日(星期二) 下午2:25
收件人: "Mo-Dabao/pyNMIC"<pyNMIC@noreply.github.com>;
抄送: "shepherdmeng"<437677587@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [Mo-Dabao/pyNMIC] 矢量边界 (#1)




@shepherdmeng
 github竟然没有提醒我有Issue！！！
 
我就在https://gadm.org/ 上找的shp文件，也不是知道上哪儿找最标准的。方便的话能提供一份或者告知上哪儿下载吗？
