### ISSUE TITLE
ValueError: cannot add coordinates with new dimensions to a DataArray

### ISSUE THREAD

**Issue by uestc-whu** [Mo-Dabao/pyMeteo#10]
您好，我尝试跑file.extract的时候会报错提示“ValueError: cannot add coordinates with new dimensions to a DataArray”，显示问题出在fy4a.py的这里“ dn_values = dn_values.assign_coords(line=range(self.line_begin, self.line_end+1),column=range(self.column_begin, self.column_end+1))”。麻烦问下具体是什么导致的呀？我不太明白，谢谢！

**Comment by Mo-Dabao** [comment]
我没有能复现你的报错。测试所用的`xarray`版本为`0.19.0`，你确认一下你`xarray`什么版本，升级能否解决报错

**Comment by uestc-whu** [comment]
恩恩应该是版本的问题，在另一台上可以跑的，谢谢啦！
