### ISSUE TITLE
绘图时的投影转换问题

### ISSUE THREAD

**Issue by hehuan710** [Mo-Dabao/pyMeteo#2]
im = self.ax.imshow(channel, cmap="gray", transform=PlateCarree, origin='upper',
                            extent=extent)
请问，channel应该是NOM的格点数据，这句是怎么把它转为为经纬度绘图的呢，也没见卫星高度和卫星星下点经纬度参数输入呢

**Comment by Mo-Dabao** [comment]
@hehuan710 
```python
        # 获取数据
        geo_range = self.geo_range.get()
        if self.fy4a_h5.channels[channelname] is None or self.fy4a_h5.geo_range != eval(geo_range):
            self.fy4a_h5.extract(channelname, geo_range=geo_range)
        channel = self.fy4a_h5.channels[channelname]
```
在fy4a.py中FY4A_H5类中有extract方法实现了根据经纬度范围提取，这个方法用的projection.py进行了经纬度到NOM的格点数据行列号的转化，是根据国家卫星气象中心的文档来写的
