### ISSUE TITLE
FY4 标称投影转等经纬度投影。

### ISSUE THREAD

**Issue by cwyanhong** [Mo-Dabao/pyMeteo#3]
请问楼主有用python实现fy4全圆盘到等经纬的转换吗?可否共享下？

**Comment by zxdawn** [comment]
@cwyanhong 我已经往satpy里面提交了pull request，后面resample就很方便了。你可以先用暂时的[头文件](https://github.com/zxdawn/FY-4/tree/master/satpy)试试。

**Comment by Mo-Dabao** [comment]
@cwyanhong 
在projection.py中实现了FY-4A标称（NOM）全圆盘（DISK）数据的行列号经纬度互转，其中
```def latlon2lc(lat, lon, resolution):
    """
    (lat, lon) → (l, c)
    resolution：文件名中的分辨率{"0500M", "1000M", "2000M", "4000M"}
    """
```
是根据传入的lat, lon求在全圆盘数据中的行列号。构造好所需要的经纬度矩阵就可以求得全圆盘数据中的行列号矩阵，索引一下就出来了。

当然这部分我已经在fy4a.py中FY4A_H5类的extract方法中实现了，可以直接阅读源码看用法
