### ISSUE TITLE
关于georange的获取

### ISSUE THREAD

**Issue by zyhgis** [Mo-Dabao/pyMeteo#4]
你好，代码里你给出了4km的georange，这个数据您从哪里获得的，500m,1km,2km的georange是多少呢？

**Comment by zxdawn** [comment]
@zyhgis 我建议可以直接读取原始的，我是用pyresample里面的geometry操作的。具体的你可以参考我为satpy提供的[脚本](https://github.com/zxdawn/FY-4/blob/master/satpy/agri_l1.py)，目前还在satpy的pull request审核。

**Comment by Mo-Dabao** [comment]
@zyhgis 
georange一般自己设置成所要的研究区域范围和分辨率就行，只不过目前假如你设置的范围超过这个静止卫星的视野会报错，等我空下来慢慢改进
