### ISSUE TITLE
Channel02为何读取出错

### ISSUE THREAD

**Issue by dodolooking** [Mo-Dabao/pyMeteo#5]

**Comment by Mo-Dabao** [comment]
因为有缺测值，我没想到啥优雅地处理缺测值的方法就啥也没处理

**Comment by dodolooking** [comment]
> 因为有缺测值，我没想到啥优雅地处理缺测值的方法就啥也没处理

`    # DISK全圆盘数据和REGC中国区域数据区别在起始行号和终止行号
        channel = self.h5file[NOMChannelname][()][self.l - self.l_begin, self.c]
        channel[channel>=65534]=0
        CALChannel = self.h5file[CALChannelname][()]  # 定标表
        self.channels[channelname] = CALChannel[channel]  # 缺测值！？`

我将大于等于65534的值都置为0，这样做可以吗？

**Comment by zxdawn** [comment]
@dodolooking 最好使用`valid_range`
https://github.com/zxdawn/FY-4/blob/6a4db42cb9930a0accb8b9954c08e7893449be74/satpy/agri_l1.py#L113-L114

**Comment by dodolooking** [comment]
``

> @dodolooking 最好使用`valid_range`
> https://github.com/zxdawn/FY-4/blob/6a4db42cb9930a0accb8b9954c08e7893449be74/satpy/agri_l1.py#L113-L114

谢谢，我也是龙王山皇家气象学院的
