### ISSUE TITLE
标称行列号和经纬度互相转换

### ISSUE THREAD

**Issue by Huangbaoru** [Mo-Dabao/pyMeteo#6]
这个标转行列号和经纬度互转，怎么确认是正确的？据文档来看国家局提供了两种方法， 查表法和公式法。 请问，你用这两种方法做过对比以确认程序#projection.py#结果正确性吗？ 谢谢。

**Comment by Mo-Dabao** [comment]
@Huangbaoru 
一开始没有用500m分辨率数据时我就用的查表法，到500m没有表可查就改用公式法了。我没有做过验证，只是出图与中国气象数据网上的图目视对比觉得一样就乐颠颠地用了

想要验证的话可以用`projection.py`中的`linecolumn2latlon`函数制作行列号和经纬度查找表，与官网的做比较

**Comment by Huangbaoru** [comment]
ok. 多谢！
