### ISSUE TITLE
行列号转换为经纬度

### ISSUE THREAD

**Issue by zyhgis** [Mo-Dabao/pyMeteo#7]
你好，我在用行列号转换经纬度时，发现会出现nan值的结果，您知道时什么原因导致的吗？

**Comment by zyhgis** [comment]
对于每种分辨率的步长，我想问一下您这样设置的依据是什么？500m一般认为是0.0045吧

**Comment by Mo-Dabao** [comment]
@zyhgis 
行列号转换经纬度时出现nan值：可能那个行列号对应的像素表示的是宇宙空间而不在气球上吧
分辨率：按需设置就行，不是固定的

**Comment by zyhgis** [comment]
谢谢，明白了。再麻烦问一个问题，定标之后的值的物理含义是什么？值的范围是[0,1.5],感觉既不是辐亮度也不是大气表观反射率，定标表里还有一个Intercept和Slope值，这两个值是否需要应用到定标中呢？谢谢。

**Comment by zxdawn** [comment]
@zyhgis Calibration总共有四种：可以参考https://github.com/zxdawn/FY-4/blob/219cb56f98260380f96f23c942a753024503b5a9/satpy/agri_l1.py#L68-L98

另外，前面6个通道，用查找表和系数算出来都是反射率，后面用查找表是亮温，用系数是辐亮度。
