### ISSUE TITLE
关于图像中出现nan的问题

### ISSUE THREAD

**Issue by icey-zhang** [Mo-Dabao/pyMeteo#8]
您好，我测试了一幅风云的图，发现波段九里面会有nan值，请问这是什么原因呢？

**Comment by Mo-Dabao** [comment]
> 您好，我测试了一幅风云的图，发现波段九里面会有nan值，请问这是什么原因呢？

我也不清楚，这可能得问国家卫星中心

**Comment by icey-zhang** [comment]
请问 我把维度设为10-55N时 为什么代码会报错误

> IndexError: index 65535 is out of bounds for axis 0 with size 1092

**Comment by Mo-Dabao** [comment]
> 请问 我把维度设为10-55N时 为什么代码会报错误
> 
> > IndexError: index 65535 is out of bounds for axis 0 with size 1092

缺测值应该在这一部分处理了才对
https://github.com/Mo-Dabao/pyMeteo/blob/ed0314e04279510df7c9eb3bd8557681891efbeb/FY4A/fy4a.py#L84-L91

你是用的旧版代码吗？

**Comment by icey-zhang** [comment]
博主，请问一下CALchannel是什么呀？

**Comment by Mo-Dabao** [comment]
> 博主，请问一下CALchannel是什么呀？

定标表
