### ISSUE TITLE
关于python环境的问题

### ISSUE THREAD

**Issue by zhangfuhan** [Mo-Dabao/pyMeteo#9]
您好，麻烦问一下，其中 from osgeo import osr 中的 osgeo如何安装呢。

查到都是安装 gdal的

conda上也查找不到这个osr和osgeo....

**Comment by Mo-Dabao** [comment]
@zhangfuhan 对，osgeo就是gdal。晚上有空的话我把GDAL换成cartopy吧

**Comment by zhangfuhan** [comment]
非常感谢🙏

**Comment by Mo-Dabao** [comment]
cartopy也是依赖proj4，但更方便绘图
